# lambda/prompts.py
"""
Message key constants for language strings.
These keys are used to lookup localized messages in language_strings.json
"""

# Help messages
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"

# Stop/Cancel messages
STOP_MESSAGE = "STOP_MESSAGE"

# Fallback messages
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"

# Success messages
DEVICE_CONTROL_SUCCESS = "DEVICE_CONTROL_SUCCESS"
SET_VALUE_SUCCESS = "SET_VALUE_SUCCESS"
SCENARIO_ACTIVATED = "SCENARIO_ACTIVATED"
SCENARIO_STOPPED = "SCENARIO_STOPPED"
SELECTED = "SELECTED"

# Error messages - Input validation
ERROR_NO_NUMBER = "ERROR_NO_NUMBER"
ERROR_NO_STRING = "ERROR_NO_STRING"
ERROR_NO_SELECTION = "ERROR_NO_SELECTION"
ERROR_NO_DURATION = "ERROR_NO_DURATION"
ERROR_NO_DATETIME = "ERROR_NO_DATETIME"
ERROR_INVALID_DURATION = "ERROR_INVALID_DURATION"
ERROR_INVALID_VALUE = "ERROR_INVALID_VALUE"
ERROR_INVALID_TYPE = "ERROR_INVALID_TYPE"

# Error messages - Missing data
ERROR_MISSING_SLOTS = "ERROR_MISSING_SLOTS"
ERROR_MISSING_VALUE = "ERROR_MISSING_VALUE"
ERROR_MISSING_SCENARIO = "ERROR_MISSING_SCENARIO"
ERROR_MISSING_DATA = "ERROR_MISSING_DATA"
ERROR_NO_DEVICE = "ERROR_NO_DEVICE"

# Error messages - Network/Communication
ERROR_NETWORK = "ERROR_NETWORK"
ERROR_NETWORK_REPROMPT = "ERROR_NETWORK_REPROMPT"
ERROR_TIMEOUT = "ERROR_TIMEOUT"
ERROR_PARSE = "ERROR_PARSE"

# Error messages - Authentication/Authorization
ERROR_401 = "ERROR_401"
ERROR_403 = "ERROR_403"

# Error messages - Configuration/System
ERROR_CONFIG = "ERROR_CONFIG"
ERROR_GENERAL = "ERROR_GENERAL"
ERROR_ACOUSTIC = "ERROR_ACOUSTIC"

# Error messages - Jeedom specific
ERROR_JEEDOM = "ERROR_JEEDOM"
ERROR_DEVICE_CONTROL = "ERROR_DEVICE_CONTROL"
ERROR_STATUS_QUERY = "ERROR_STATUS_QUERY"
ERROR_SET_VALUE = "ERROR_SET_VALUE"
ERROR_SCENARIO = "ERROR_SCENARIO"
ERROR_SCENARIO_LIST = "ERROR_SCENARIO_LIST"
ERROR_SCENARIO_STOP = "ERROR_SCENARIO_STOP"