# lambda/prompts.py

# Success messages
OKAY = "OKAY"
SELECTED = "SELECTED"
DEVICE_CONTROL_SUCCESS = "DEVICE_CONTROL_SUCCESS"
SET_VALUE_SUCCESS = "SET_VALUE_SUCCESS"
SCENARIO_ACTIVATED = "SCENARIO_ACTIVATED"

# Help and guidance
HELP_MESSAGE = "HELP_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"

# Error messages
ERROR_GENERAL = "ERROR_GENERAL"
ERROR_CONFIG = "ERROR_CONFIG"
ERROR_NETWORK = "ERROR_NETWORK"
ERROR_PARSE = "ERROR_PARSE"
ERROR_ACOUSTIC = "ERROR_ACOUSTIC"
ERROR_401 = "ERROR_401"
ERROR_404 = "ERROR_404"
ERROR_400 = "ERROR_400"

# Slot errors
ERROR_MISSING_SLOTS = "ERROR_MISSING_SLOTS"
ERROR_MISSING_SCENARIO = "ERROR_MISSING_SCENARIO"
ERROR_INVALID_VALUE = "ERROR_INVALID_VALUE"
ERROR_MISSING_DATA = "ERROR_MISSING_DATA"

# Data errors
ERROR_NO_NUMBER = "ERROR_NO_NUMBER"
ERROR_NO_STRING = "ERROR_NO_STRING"
ERROR_NO_SELECTION = "ERROR_NO_SELECTION"
ERROR_NO_DURATION = "ERROR_NO_DURATION"
ERROR_INVALID_DURATION = "ERROR_INVALID_DURATION"
ERROR_NO_DATETIME = "ERROR_NO_DATETIME"